services:
  postgres:
    image: postgres:15-alpine
    container_name: misp-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: misp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
        context: .
        dockerfile: ./apps/frontend/Dockerfile
    container_name: misp-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/frontend:/app
    depends_on:
      - backend
    restart: unless-stopped
    profiles:
      - ci

  backend:
    build:
      context: . 
      dockerfile: ./apps/backend/Dockerfile  
    container_name: misp-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./apps/backend:/app
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - ci

  # field-ops-pwa:
  #   build:
  #     context: .
  #     dockerfile: ./apps/field-ops-pwa/Dockerfile
  #   container_name: misp-field-ops-pwa
  #   ports:
  #     - "3002:3000"
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - ./apps/field-ops-pwa:/app
  #   depends_on:
  #     - backend
  #   restart: unless-stopped
  #   profiles:
  #     - ci

volumes:
  pgdata: